name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  PREFIX: x86_64-w64-mingw32

jobs:
  Windows-x86_64:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4.2.2

     - name: Update package list
       run: sudo apt-get update

     - name: Install Dependencies
       run: sudo apt-get install -y gcc-mingw-w64-x86-64 binutils-mingw-w64-x86-64

     - name: Build SRB2
       run: make -C src/ --keep-going  -j$(nproc) MINGW64=1

     - name: Upload Artifacts
       uses: actions/upload-artifact@v4.6.1
       with:
        name: srb2-windows-x86_64
        path: |
          bin/
          src/comptime.h
  Windows-x86:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4.2.2

     - name: Update package list
       run: sudo apt-get update

     - name: Install Dependencies
       run: sudo apt-get install -y gcc-mingw-w64-i686 binutils-mingw-w64-i686

     - name: Build SRB2
       run: make -C src/ --keep-going  -j$(nproc) MINGW=1

     - name: Upload Artifacts
       uses: actions/upload-artifact@v4.6.1
       with:
        name: srb2-windows-x86
        path: |
          bin/
          src/comptime.h
