# yes, this fork is made in 64-bit in mind. if you don't like exclusively 64-bit stuff, then compile it yourself

name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  PREFIX: x86_64-w64-mingw32

jobs:
  Windows-x64:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@main

     - name: Update package list
       run: sudo apt-get update

     - name: Install Dependencies
       run: sudo apt-get install -y gcc-mingw-w64-x86-64 binutils-mingw-w64-x86-64

     - name: Build SRB2
       run: make -C src/ --keep-going  -j$(nproc) MINGW64=1

     - name: Upload Artifacts
       uses: actions/upload-artifact@main
       with:
        name: srb2-tprs-windows-x64
        path: |
          bin/
          src/comptime.h
