name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CC: gcc
  PREFIX: x86_64-w64-mingw32

jobs:
  Ubuntu-AMD64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2

    - name: Update package list
      run: sudo apt-get update

    - name: Install Dependencies
      run: sudo apt-get install -y libsdl2-mixer-dev libpng-dev libcurl4-openssl-dev libgme-dev libopenmpt-dev libminiupnpc-dev

    - name: Build SRB2
      run: make -C src/ --keep-going -j$(nproc) LINUX64=1

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4.6.1
      with:
        name: srb2-linux-x86_64
        path: |
          bin/
          src/comptime.h
  Ubuntu-ARM64:
    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v4.2.2

    - name: Update package list
      run: sudo apt-get update

    - name: Install Dependencies
      run: sudo apt-get install -y libsdl2-mixer-dev libpng-dev libcurl4-openssl-dev libgme-dev libopenmpt-dev libminiupnpc-dev

    - name: Build SRB2
      run: make -C src/ --keep-going -j$(nproc) LINUX64=1

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4.6.1
      with:
        name: srb2-linux-arm64
        path: |
          bin/
          src/comptime.h
  Windows-x86_64:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4.2.2

     - name: Update package list
       run: sudo apt-get update

     - name: Install Dependencies
       run: sudo apt-get install -y gcc-mingw-w64-x86-64 binutils-mingw-w64-x86-64

     - name: Build SRB2
       run: make -C src/ --keep-going  -j$(nproc) MINGW64=1

     - name: Upload Artifacts
       uses: actions/upload-artifact@v4.6.1
       with:
        name: srb2-windows-x86_64
        path: |
          bin/
          src/comptime.h
  Windows-x86:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4.2.2

     - name: Update package list
       run: sudo apt-get update

     - name: Install Dependencies
       run: sudo apt-get install -y gcc-mingw-w64-x86-64 binutils-mingw-w64-x86-64

     - name: Build SRB2
       run: make -C src/ --keep-going  -j$(nproc) MINGW64=1

     - name: Upload Artifacts
       uses: actions/upload-artifact@v4.6.1
       with:
        name: srb2-windows-x86_64
        path: |
          bin/
          src/comptime.h
